// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
class TestMsg;
struct TestMsgDefaultTypeInternal;
extern TestMsgDefaultTypeInternal _TestMsg_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::TestMsg* Arena::CreateMaybeMessage<::TestMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class TestMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:TestMsg) */ {
 public:
  inline TestMsg() : TestMsg(nullptr) {}
  ~TestMsg() override;
  explicit PROTOBUF_CONSTEXPR TestMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TestMsg(const TestMsg& from);
  TestMsg(TestMsg&& from) noexcept
    : TestMsg() {
    *this = ::std::move(from);
  }

  inline TestMsg& operator=(const TestMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline TestMsg& operator=(TestMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TestMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const TestMsg* internal_default_instance() {
    return reinterpret_cast<const TestMsg*>(
               &_TestMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TestMsg& a, TestMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(TestMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TestMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TestMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TestMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TestMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TestMsg& from) {
    TestMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "TestMsg";
  }
  protected:
  explicit TestMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPersonFieldNumber = 3,
    kMsgFieldNumber = 1,
    kIndexFieldNumber = 2,
  };
  // repeated string person = 3;
  int person_size() const;
  private:
  int _internal_person_size() const;
  public:
  void clear_person();
  const std::string& person(int index) const;
  std::string* mutable_person(int index);
  void set_person(int index, const std::string& value);
  void set_person(int index, std::string&& value);
  void set_person(int index, const char* value);
  void set_person(int index, const char* value, size_t size);
  std::string* add_person();
  void add_person(const std::string& value);
  void add_person(std::string&& value);
  void add_person(const char* value);
  void add_person(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& person() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_person();
  private:
  const std::string& _internal_person(int index) const;
  std::string* _internal_add_person();
  public:

  // string msg = 1;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // int32 index = 2;
  void clear_index();
  int32_t index() const;
  void set_index(int32_t value);
  private:
  int32_t _internal_index() const;
  void _internal_set_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:TestMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> person_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    int32_t index_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestMsg

// string msg = 1;
inline void TestMsg::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& TestMsg::msg() const {
  // @@protoc_insertion_point(field_get:TestMsg.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void TestMsg::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:TestMsg.msg)
}
inline std::string* TestMsg::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:TestMsg.msg)
  return _s;
}
inline const std::string& TestMsg::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void TestMsg::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* TestMsg::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* TestMsg::release_msg() {
  // @@protoc_insertion_point(field_release:TestMsg.msg)
  return _impl_.msg_.Release();
}
inline void TestMsg::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:TestMsg.msg)
}

// int32 index = 2;
inline void TestMsg::clear_index() {
  _impl_.index_ = 0;
}
inline int32_t TestMsg::_internal_index() const {
  return _impl_.index_;
}
inline int32_t TestMsg::index() const {
  // @@protoc_insertion_point(field_get:TestMsg.index)
  return _internal_index();
}
inline void TestMsg::_internal_set_index(int32_t value) {
  
  _impl_.index_ = value;
}
inline void TestMsg::set_index(int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:TestMsg.index)
}

// repeated string person = 3;
inline int TestMsg::_internal_person_size() const {
  return _impl_.person_.size();
}
inline int TestMsg::person_size() const {
  return _internal_person_size();
}
inline void TestMsg::clear_person() {
  _impl_.person_.Clear();
}
inline std::string* TestMsg::add_person() {
  std::string* _s = _internal_add_person();
  // @@protoc_insertion_point(field_add_mutable:TestMsg.person)
  return _s;
}
inline const std::string& TestMsg::_internal_person(int index) const {
  return _impl_.person_.Get(index);
}
inline const std::string& TestMsg::person(int index) const {
  // @@protoc_insertion_point(field_get:TestMsg.person)
  return _internal_person(index);
}
inline std::string* TestMsg::mutable_person(int index) {
  // @@protoc_insertion_point(field_mutable:TestMsg.person)
  return _impl_.person_.Mutable(index);
}
inline void TestMsg::set_person(int index, const std::string& value) {
  _impl_.person_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:TestMsg.person)
}
inline void TestMsg::set_person(int index, std::string&& value) {
  _impl_.person_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:TestMsg.person)
}
inline void TestMsg::set_person(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.person_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:TestMsg.person)
}
inline void TestMsg::set_person(int index, const char* value, size_t size) {
  _impl_.person_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:TestMsg.person)
}
inline std::string* TestMsg::_internal_add_person() {
  return _impl_.person_.Add();
}
inline void TestMsg::add_person(const std::string& value) {
  _impl_.person_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:TestMsg.person)
}
inline void TestMsg::add_person(std::string&& value) {
  _impl_.person_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:TestMsg.person)
}
inline void TestMsg::add_person(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _impl_.person_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:TestMsg.person)
}
inline void TestMsg::add_person(const char* value, size_t size) {
  _impl_.person_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:TestMsg.person)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
TestMsg::person() const {
  // @@protoc_insertion_point(field_list:TestMsg.person)
  return _impl_.person_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
TestMsg::mutable_person() {
  // @@protoc_insertion_point(field_mutable_list:TestMsg.person)
  return &_impl_.person_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
